### ISSUE TITLE
basic python help needed

### ISSUE THREAD

**Issue by wwieder** [NCAR/CTSM-Tutorial#36]
I started working on a [quick plot tutorial](https://github.com/NCAR/CTSM-Tutorial/blob/480aa64751b6fcc3b430c324ebaa161f7c48e5e2/notebooks/QuickPlot_NEON.ipynb)

Specifically I'm setting up a path the the folder where files are located
```
neon_site = 'CPER'  #NEON site we're going to look at
archive = '~/scratch/NEON_cases/archive/'  #Path to the directory with archived cases
data_folder = archive + neon_site + '.transient/lnd/hist'  #directory with input data we're going to open
data_folder
```
Here all looks correct, pointing to `~/scratch/NEON_cases/archive/CPER.transient/lnd/hist`

When I try to glob this data folder, I only get an empty list in return
```
glob(os.path.join(data_folder,'*.nc'))
```
[ ]

Suggestions here would be most helpful.

**Comment by wwieder** [comment]
@teaganking or @samsrabin can you help with this basic question?

**Comment by samsrabin** [comment]
Does it work if you write out the full path to your home directory instead of using `~`?

If not, and sorry if this is insulting but it's always good to check: Is `~/scratch/NEON_cases/archive/CPER.transient/lnd/hist` actually a directory on your system?

**Comment by wwieder** [comment]
oh you're right, it doesn't like the ~ and the softlink that's in home to my scratch directory.

**Comment by wwieder** [comment]
is there another convenient way to do this in a way that's agnostic to running in the cloud or on cheyenne.  I've been using a softlink in home to go to scratch `~/scratch`. This let's other parts of the tutorial work on either machine (once users add a similar to softlink to `/glade/scratch/$USER/`.  Is there a similar python work around?

**Comment by samsrabin** [comment]
Not sure if this will work, but try putting the path with `~/scratch` through `os.path.realpath()`.

Failing that, you could instruct users to (bash) `export SCRATCH="/path/to/scratch/dir"` before starting Python. Then in the Python script they could do `os.environ["SCRATCH"]` to get its value.

**Comment by wwieder** [comment]
yep, `os.path.realpath()` gets rid the the ~, but glob still does't like the soft link that it points to, I'll keep trying.  Thanks for your suggestions.

**Comment by samsrabin** [comment]
Okay, it looks like this should work:
```python
os.path.realpath(os.path.expanduser("~/scratch"))
```
For example, on Cheyenne:
```
>>> os.path.realpath(os.path.expanduser("~samrabin/inputdata"))
'/glade/p/cesmdata/cseg/inputdata'
```
